### ISSUE TITLE
不支持新版的chatglm

### ISSUE THREAD

**Issue by zx2021** [ypwhs/CreativeChatGLM#14]
更新一下前段时间的chatglm模型文件之后运行报错如下
Traceback (most recent call last):
  File "D:\Desktop\CreativeChatGLM-master\app.py", line 18, in <module>
    predictor = ChatGLM(model_name)
  File "D:\Desktop\CreativeChatGLM-master\predictors\chatglm2.py", line 40, in __init__
    model = ChatGLMForConditionalGeneration.from_pretrained(
  File "D:\Python\Python310\lib\site-packages\transformers\modeling_utils.py", line 2646, in from_pretrained
    ) = cls._load_pretrained_model(
  File "D:\Python\Python310\lib\site-packages\transformers\modeling_utils.py", line 3019, in _load_pretrained_model
    raise RuntimeError(f"Error(s) in loading state_dict for {model.__class__.__name__}:\n\t{error_msg}")
RuntimeError: Error(s) in loading state_dict for ChatGLMForConditionalGeneration:
        size mismatch for transformer.word_embeddings.weight: copying a param with shape torch.Size([130528, 4096]) from checkpoint, the shape in current model is torch.Size([150528, 4096]).
        size mismatch for lm_head.weight: copying a param with shape torch.Size([130528, 4096]) from checkpoint, the shape in current model is torch.Size([150528, 4096]).
        You may consider adding `ignore_mismatched_sizes=True` in the model `from_pretrained` method.
cuda11.8
python3.10
pytorch2.0.0
windows10

**Comment by zx2021** [comment]
我是说int4-slim版

**Comment by ypwhs** [comment]
你说的是这个模型吧：https://github.com/silverriver/ChatGLM-6B-Slim

我尝试一下。

**Comment by ypwhs** [comment]
修复了，你试试最新版：

![](https://user-images.githubusercontent.com/10473170/229671882-5848dbc0-3e50-4703-8048-00b6d0a68a59.png)
